- name: Install env
  hosts: all
  user: ubuntu
  become: yes

  tasks:
    - name: wait for ssh
        wait_for:
          port: 22
          delay: 10

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install docker
      apt:
        name: docker.io
        update_cache: yes
        state: present

- name: Instal build env
  hosts: MAVEN
  user: ubuntu
  become: yes

  tasks:
    - name: wait for ssh
      wait_for:
        port: 22
        delay: 10

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Create Directory /home/Project
      file:
        path: /home/Project
        state: directory

    - name: Git Clone
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /home/Project
        clone: yes

