- name: Install env
  hosts: all
  user: ubuntu
  become: yes

  tasks:
    - name: wait for ssh
        wait_for:
          port: 22
          delay: 10

    - name: Install Git
      apt: name={{ item }} state=installed update_cache=yes
        with_items:
          - git
          - docker.io

#    - name: Install docker
#      apt:
#        name: docker.io
#        update_cache: yes
#        state: present

- name: Instal build env
  hosts: MAVEN
  user: ubuntu
  become: yes

  tasks:
    - name: wait for ssh
      wait_for:
        port: 22
        delay: 10

    - name: Install Maven
      apt: name={{ item }} state=installed
        with_items:
          - maven
          - pass

    - name: Recursively delete existing Directory /home/ubuntu/artifact
        file:
          path: /home/ubuntu/artifact
          state: absent

    - name: Create Directory /home/ubuntu/artifact
      file:
        path: /home/ubuntu/artifact
        state: directory

    - name: Git Clone
      git:
        repo: https://github.com/integrator-sev/boxfuse-origin.git
        dest: /home/ubuntu/artifact
        clone: yes

